version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/config/php/Dockerfile
    env_file:
      - .env
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "${DOCKER_PUSHER_APP_PORT}:6001"
      - "${DOCKER_SERVER_PORT}:8000"
    networks:
      - app-network

  # Data persistence service layer
  mysql:
    image: mysql:5.5.62
    env_file:
      - .env
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local